### ISSUE TITLE
Build Failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by Taigavick** [Astron/Astron#416]
I get the following error at ```[ 39%] Building CXX object CMakeFiles/astrond.dir/src/core/global.cpp.o``` when compiling the latest build of Astron. The LibUV library I am using is from the Ubuntu package, libuv-dev.

```
/root/Astron/src/core/global.cpp:12:34:   required from here
/root/Astron/src/deps/uvw/uvw/handle.hpp:170:28: error: 'uv_has_ref' was not declared in this scope
CMakeFiles/astrond.dir/build.make:62: recipe for target 'CMakeFiles/astrond.dir/src/core/global.cpp.o' failed
make[2]: *** [CMakeFiles/astrond.dir/src/core/global.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/astrond.dir/all' failed
make[1]: *** [CMakeFiles/astrond.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Psychotropos** [comment]
Should be fixed as of commit 84a17bc, could you confirm?

**Comment by Taigavick** [comment]
Thanks for looking into the issue. Unfortunately, I am still getting the same error. I have recloned Astron, updated apt-get packages, and even reinstalled libuv-dev.

**Comment by Taigavick** [comment]
I decided to build LibUV from the source and it worked. Thanks for your help!
